"""
D5 - Fredkin with Control in Centre (Cruz, Murta et al)
Source: LNN-friendly layout with q1 as control (middle qubit)
Exact: Yes | Ancilla: None | Uses: CX, T, Tdg, S, Sdg, SX, SXdg, H, Z, X
q1 = control, q0/q2 = targets (control bit is in the centre)
"""
from qiskit import QuantumCircuit


def build() -> QuantumCircuit:
    qc = QuantumCircuit(3, name="D5_Paper1_FigC")

    qc.t(1)
    qc.s(1)
    qc.s(2)
    qc.sx(1)
    qc.sxdg(2)
    qc.cx(1, 2)
    qc.sdg(1)
    qc.sdg(2)
    qc.cx(0, 1)
    qc.sx(1)
    qc.sxdg(2)
    qc.s(0)
    qc.sdg(1)
    qc.cx(1, 2)
    qc.h(0)
    qc.h(1)
    qc.t(0)
    qc.tdg(1)
    qc.sdg(1)
    qc.s(2)
    qc.h(0)
    qc.h(1)
    qc.z(0)
    qc.s(1)
    qc.cx(0, 1)
    qc.sx(0)
    qc.sx(1)
    qc.cx(1, 2)
    qc.cx(0, 1)
    qc.sdg(1)
    qc.h(0)
    qc.h(1)
    qc.h(2)
    qc.t(0)
    qc.tdg(1)
    qc.s(2)
    qc.cx(2, 1)
    qc.s(0)
    qc.tdg(1)
    qc.t(2)
    qc.h(0)
    qc.h(1)
    qc.h(2)
    qc.z(0)
    qc.s(1)
    qc.s(2)
    qc.cx(0, 1)
    qc.sx(0)
    qc.x(1)
    qc.sx(2)
    qc.cx(1, 2)
    qc.cx(0, 1)

    return qc
